### ISSUE TITLE
ModuleNotFoundError: No module named 'tracker_utils'

### ISSUE THREAD

**Issue by LarryDong** [uzh-rpg/rpg_feature_tracking_analysis#2]
When running 
> python evaluate_tracks.py ...

command, the program failed: 

> Traceback (most recent call last):
>   File "evaluate_tracks.py", line 10, in <module>
>     from big_pun.tracker import Tracker
>   File "/home/larrydong/codeGit/rpg_feature_tracking_analysis/big_pun/tracker.py", line 3, in <module>
>     from tracker_utils import projectLandmarks
> ModuleNotFoundError: No module named 'tracker_utils'

I think I've installed correctly. Any solutions? Thanks.

**Comment by LarryDong** [comment]
I've fixed this problem.
This happened when I "source venv/bin/activate" and in (venv) environment.
After quit this environment, all modules can be found.
